#!/usr/bin/env python
###############################################################################
# (c) Copyright 2000-2018 CERN for the benefit of the LHCb Collaboration      #
#                                                                             #
# This software is distributed under the terms of the GNU General Public      #
# Licence version 3 (GPL Version 3), copied verbatim in the file "COPYING".   #
#                                                                             #
# In applying this licence, CERN does not waive the privileges and immunities #
# granted to it by virtue of its status as an Intergovernmental Organization  #
# or submit itself to any jurisdiction.                                       #
###############################################################################
# =============================================================================
# $Id:$ 
# =============================================================================
## @file dump_ParticleProperties
#
#  Trivial script to dump the particle properties 
#
#  @date   2010-10-22
#  @author Vanya BELYAEV Ivan.Belyaev@nikhef.nl
#
#  Last modification $Date: 2010-09-10 14:04:49 $
#                 by $Author: ibelyaev $
# =============================================================================
import sys 
from   PartProp.DumpParticleProperties import dump
dump ( [ a for a in sys.argv[1:] if '--' != a ] )


# =============================================================================
# The END 
# =============================================================================


