#!/usr/bin/env python
# =============================================================================
# $Id:$ 
# =============================================================================
## @file dump_ParticleProperties
#
#  Trivial script to dump the particle properties 
#
#  @date   2010-10-22
#  @author Vanya BELYAEV Ivan.Belyaev@nikhef.nl
#
#  Last modification $Date: 2010-09-10 14:04:49 $
#                 by $Author: ibelyaev $
# =============================================================================
import sys 
from   PartProp.DumpParticleProperties import dump
dump ( [ a for a in sys.argv[1:] if '--' != a ] )


# =============================================================================
# The END 
# =============================================================================


