###############################################################################
# (c) Copyright 2018 CERN for the benefit of the LHCb Collaboration           #
#                                                                             #
# This software is distributed under the terms of the GNU General Public      #
# Licence version 3 (GPL Version 3), copied verbatim in the file "COPYING".   #
#                                                                             #
# In applying this licence, CERN does not waive the privileges and immunities #
# granted to it by virtue of its status as an Intergovernmental Organization  #
# or submit itself to any jurisdiction.                                       #
###############################################################################
check-copyright:
  image: gitlab-registry.cern.ch/ci-tools/ci-worker:cc7
  script:
    - curl -o check_copyright.py "https://gitlab.cern.ch/lhcb-core/LbDevTools/raw/master/LbDevTools/CopyrightCheck.py?inline=false"
    - python check_copyright.py origin/master
build:
  script:
    # trigger to lb-dev repo
    # requires the secret variable LBDEVTOKEN
    - curl -X POST -F token=${LBDEVTOKEN} -F ref=master -F "variables[USEURL]=${CI_REPOSITORY_URL}" -F "variables[USECOMMIT]=${CI_COMMIT_SHA}" -F "variables[LBUSE]=LHCb" https://gitlab.cern.ch/api/v4/projects/43169/trigger/pipeline
